services:
  app:
    build:
      context: .
      target: app
    env_file: ./.env
    shm_size: '1gb'
    ports:
      - '${DEV_PORT}:3000'
    volumes:
      - .:/app:z
      - type: bind
        source: ${LIVE_BROWSER_CONTAINER_DATA_HOST_DIR:-./.dev/live-browser-persist}
        target: /app/.dev/live-browser-persist
      - node-dev:/home/node/dev
    environment:
      NODE_ENV: development
      NODE_OPTIONS: '--max-old-space-size=6144'
      HOST_MACHINE: host.docker.internal
      DEVCONTAINER_KEEPALIVE: '1'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - climate-map-network

networks:
  climate-map-network:
    name: climate-map-network
    external: true

volumes:
  node-dev:
    driver: local
