[build]
  command = "NEXT_PUBLIC_URL=$DEPLOY_PRIME_URL NEXT_PUBLIC_COMPILED_APPLETS=main,energiakartta,hiilikartta,luonnonmetsakartat yarn run build"

[context."hiilikartta_deploy"]
  command = "NEXT_PUBLIC_URL=$DEPLOY_PRIME_URL NEXT_PUBLIC_COMPILED_APPLETS=hiilikartta yarn run build"

[context."luonnonmetsakartat_deploy"]
  command = "NEXT_PUBLIC_URL=$DEPLOY_PRIME_URL NEXT_PUBLIC_COMPILED_APPLETS=luonnonmetsakartat yarn run build"
