export const SIDEBAR_CLOSED_WIDTH = 64

export const SIDEBAR_PADDING_REM = 2.75
export const MOBILE_SIDEBAR_PADDING_REM = 1.5
export const MOBILE_BREAKPOINT_PX = 600
export const MOBILE_BREAKPOINT_KEY = 'mobile' as const
export const DESKTOP_BREAKPOINT_KEY = 'desktop' as const

export const SCROLLBAR_WIDTH_REM = 0.6

export const SIDEBAR_PADDING_WITH_SCROLLBAR_REM =
  SIDEBAR_PADDING_REM + SCROLLBAR_WIDTH_REM
