/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleMapRouteRouteImport } from './routes/$locale/_map/route'
import { Route as LocaleMapIndexRouteImport } from './routes/$locale/_map/index'
import { Route as LocaleDevComponentFixturesRouteRouteImport } from './routes/$locale/dev/component-fixtures/route'
import { Route as LocaleAddsLoginRouteRouteImport } from './routes/$locale/adds/login/route'
import { Route as LocaleDevComponentFixturesIndexRouteImport } from './routes/$locale/dev/component-fixtures/index'
import { Route as LocaleAddsLoginIndexRouteImport } from './routes/$locale/adds/login/index'
import { Route as LocaleAddsLoginCallbackRouteImport } from './routes/$locale/adds/login/callback'
import { Route as LocaleMapappletsUiBaselineRouteRouteImport } from './routes/$locale/_map/(applets)/ui-baseline/route'
import { Route as LocaleMapappletsLuonnonmetsakartatRouteRouteImport } from './routes/$locale/_map/(applets)/luonnonmetsakartat/route'
import { Route as LocaleMapappletsForestsRouteRouteImport } from './routes/$locale/_map/(applets)/forests/route'
import { Route as LocaleMapappletsEnergyRouteRouteImport } from './routes/$locale/_map/(applets)/energy/route'
import { Route as LocaleMapappletsCarbonRouteRouteImport } from './routes/$locale/_map/(applets)/carbon/route'
import { Route as LocaleMapappletsUiBaselineIndexRouteImport } from './routes/$locale/_map/(applets)/ui-baseline/index'
import { Route as LocaleMapappletsLuonnonmetsakartatIndexRouteImport } from './routes/$locale/_map/(applets)/luonnonmetsakartat/index'
import { Route as LocaleMapappletsForestsIndexRouteImport } from './routes/$locale/_map/(applets)/forests/index'
import { Route as LocaleMapappletsEnergyIndexRouteImport } from './routes/$locale/_map/(applets)/energy/index'
import { Route as LocaleMapappletsCarbonIndexRouteImport } from './routes/$locale/_map/(applets)/carbon/index'
import { Route as LocaleDevComponentFixturesFixtureIdStateIdRouteImport } from './routes/$locale/dev/component-fixtures/$fixtureId/$stateId'
import { Route as LocaleMapappletsUiBaselinePanelsRouteImport } from './routes/$locale/_map/(applets)/ui-baseline/panels'
import { Route as LocaleMapappletsUiBaselineNotificationsRouteImport } from './routes/$locale/_map/(applets)/ui-baseline/notifications'
import { Route as LocaleMapappletsUiBaselineNodeFlowRouteImport } from './routes/$locale/_map/(applets)/ui-baseline/node-flow'
import { Route as LocaleMapappletsUiBaselineModalsRouteImport } from './routes/$locale/_map/(applets)/ui-baseline/modals'
import { Route as LocaleMapappletsUiBaselineInputsRouteImport } from './routes/$locale/_map/(applets)/ui-baseline/inputs'
import { Route as LocaleMapappletsUiBaselineDropdownsRouteImport } from './routes/$locale/_map/(applets)/ui-baseline/dropdowns'
import { Route as LocaleMapappletsUiBaselineDrawingRouteImport } from './routes/$locale/_map/(applets)/ui-baseline/drawing'
import { Route as LocaleMapappletsUiBaselineContentRouteImport } from './routes/$locale/_map/(applets)/ui-baseline/content'
import { Route as LocaleMapappletsUiBaselineButtonsTogglesRouteImport } from './routes/$locale/_map/(applets)/ui-baseline/buttons-toggles'
import { Route as LocaleMapappletsUiBaselineButtonsRouteImport } from './routes/$locale/_map/(applets)/ui-baseline/buttons'
import { Route as LocaleMapappletsCarbonReportRouteImport } from './routes/$locale/_map/(applets)/carbon/report'
import { Route as LocaleMapappletsLuonnonmetsakartatAdminRouteRouteImport } from './routes/$locale/_map/(applets)/luonnonmetsakartat/admin/route'
import { Route as LocaleMapappletsCarbonPlansRouteRouteImport } from './routes/$locale/_map/(applets)/carbon/plans/route'
import { Route as LocaleMapappletsLuonnonmetsakartatAdminIndexRouteImport } from './routes/$locale/_map/(applets)/luonnonmetsakartat/admin/index'
import { Route as LocaleMapappletsCarbonPlansIndexRouteImport } from './routes/$locale/_map/(applets)/carbon/plans/index'
import { Route as LocaleMapappletsLuonnonmetsakartatAdminTuoRouteImport } from './routes/$locale/_map/(applets)/luonnonmetsakartat/admin/tuo'
import { Route as LocaleMapappletsLuonnonmetsakartatAdminImportRouteImport } from './routes/$locale/_map/(applets)/luonnonmetsakartat/admin/import'
import { Route as LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRouteImport } from './routes/$locale/_map/(applets)/luonnonmetsakartat/admin/taso/route'
import { Route as LocaleMapappletsCarbonPlansPlanIdRouteRouteImport } from './routes/$locale/_map/(applets)/carbon/plans/$planId/route'
import { Route as LocaleMapappletsCarbonPlansPlanIdIndexRouteImport } from './routes/$locale/_map/(applets)/carbon/plans/$planId/index'
import { Route as LocaleMapappletsLuonnonmetsakartatAdminTasoSplatRouteImport } from './routes/$locale/_map/(applets)/luonnonmetsakartat/admin/taso/$'
import { Route as LocaleMapappletsCarbonPlansPlanIdAreasRouteImport } from './routes/$locale/_map/(applets)/carbon/plans/$planId/areas'
import { Route as LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRouteImport } from './routes/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug/route'
import { Route as LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugIndexRouteImport } from './routes/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug/index'
import { Route as LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugSettingsRouteImport } from './routes/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug/settings'
import { Route as LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugPicturesRouteImport } from './routes/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug/pictures'
import { ServerRoute as ApiUserinfoServerRouteImport } from './routes/api/userinfo'
import { ServerRoute as ApiLuonnonmetsakartatSplatServerRouteImport } from './routes/api/luonnonmetsakartat/$'
import { ServerRoute as ApiHiilikarttaSplatServerRouteImport } from './routes/api/hiilikartta/$'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'
import { ServerRoute as ApiMapCoreMmlTmsZXYServerRouteImport } from './routes/api/map/core/mml/tms/$z/$x/$y'

const rootServerRouteImport = createServerRootRoute()

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleMapRouteRoute = LocaleMapRouteRouteImport.update({
  id: '/_map',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleMapIndexRoute = LocaleMapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleMapRouteRoute,
} as any)
const LocaleDevComponentFixturesRouteRoute =
  LocaleDevComponentFixturesRouteRouteImport.update({
    id: '/dev/component-fixtures',
    path: '/dev/component-fixtures',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleAddsLoginRouteRoute = LocaleAddsLoginRouteRouteImport.update({
  id: '/adds/login',
  path: '/adds/login',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDevComponentFixturesIndexRoute =
  LocaleDevComponentFixturesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleDevComponentFixturesRouteRoute,
  } as any)
const LocaleAddsLoginIndexRoute = LocaleAddsLoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleAddsLoginRouteRoute,
} as any)
const LocaleAddsLoginCallbackRoute = LocaleAddsLoginCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LocaleAddsLoginRouteRoute,
} as any)
const LocaleMapappletsUiBaselineRouteRoute =
  LocaleMapappletsUiBaselineRouteRouteImport.update({
    id: '/(applets)/ui-baseline',
    path: '/ui-baseline',
    getParentRoute: () => LocaleMapRouteRoute,
  } as any)
const LocaleMapappletsLuonnonmetsakartatRouteRoute =
  LocaleMapappletsLuonnonmetsakartatRouteRouteImport.update({
    id: '/(applets)/luonnonmetsakartat',
    path: '/luonnonmetsakartat',
    getParentRoute: () => LocaleMapRouteRoute,
  } as any)
const LocaleMapappletsForestsRouteRoute =
  LocaleMapappletsForestsRouteRouteImport.update({
    id: '/(applets)/forests',
    path: '/forests',
    getParentRoute: () => LocaleMapRouteRoute,
  } as any)
const LocaleMapappletsEnergyRouteRoute =
  LocaleMapappletsEnergyRouteRouteImport.update({
    id: '/(applets)/energy',
    path: '/energy',
    getParentRoute: () => LocaleMapRouteRoute,
  } as any)
const LocaleMapappletsCarbonRouteRoute =
  LocaleMapappletsCarbonRouteRouteImport.update({
    id: '/(applets)/carbon',
    path: '/carbon',
    getParentRoute: () => LocaleMapRouteRoute,
  } as any)
const LocaleMapappletsUiBaselineIndexRoute =
  LocaleMapappletsUiBaselineIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleMapappletsUiBaselineRouteRoute,
  } as any)
const LocaleMapappletsLuonnonmetsakartatIndexRoute =
  LocaleMapappletsLuonnonmetsakartatIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleMapappletsLuonnonmetsakartatRouteRoute,
  } as any)
const LocaleMapappletsForestsIndexRoute =
  LocaleMapappletsForestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleMapappletsForestsRouteRoute,
  } as any)
const LocaleMapappletsEnergyIndexRoute =
  LocaleMapappletsEnergyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleMapappletsEnergyRouteRoute,
  } as any)
const LocaleMapappletsCarbonIndexRoute =
  LocaleMapappletsCarbonIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleMapappletsCarbonRouteRoute,
  } as any)
const LocaleDevComponentFixturesFixtureIdStateIdRoute =
  LocaleDevComponentFixturesFixtureIdStateIdRouteImport.update({
    id: '/$fixtureId/$stateId',
    path: '/$fixtureId/$stateId',
    getParentRoute: () => LocaleDevComponentFixturesRouteRoute,
  } as any)
const LocaleMapappletsUiBaselinePanelsRoute =
  LocaleMapappletsUiBaselinePanelsRouteImport.update({
    id: '/panels',
    path: '/panels',
    getParentRoute: () => LocaleMapappletsUiBaselineRouteRoute,
  } as any)
const LocaleMapappletsUiBaselineNotificationsRoute =
  LocaleMapappletsUiBaselineNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => LocaleMapappletsUiBaselineRouteRoute,
  } as any)
const LocaleMapappletsUiBaselineNodeFlowRoute =
  LocaleMapappletsUiBaselineNodeFlowRouteImport.update({
    id: '/node-flow',
    path: '/node-flow',
    getParentRoute: () => LocaleMapappletsUiBaselineRouteRoute,
  } as any)
const LocaleMapappletsUiBaselineModalsRoute =
  LocaleMapappletsUiBaselineModalsRouteImport.update({
    id: '/modals',
    path: '/modals',
    getParentRoute: () => LocaleMapappletsUiBaselineRouteRoute,
  } as any)
const LocaleMapappletsUiBaselineInputsRoute =
  LocaleMapappletsUiBaselineInputsRouteImport.update({
    id: '/inputs',
    path: '/inputs',
    getParentRoute: () => LocaleMapappletsUiBaselineRouteRoute,
  } as any)
const LocaleMapappletsUiBaselineDropdownsRoute =
  LocaleMapappletsUiBaselineDropdownsRouteImport.update({
    id: '/dropdowns',
    path: '/dropdowns',
    getParentRoute: () => LocaleMapappletsUiBaselineRouteRoute,
  } as any)
const LocaleMapappletsUiBaselineDrawingRoute =
  LocaleMapappletsUiBaselineDrawingRouteImport.update({
    id: '/drawing',
    path: '/drawing',
    getParentRoute: () => LocaleMapappletsUiBaselineRouteRoute,
  } as any)
const LocaleMapappletsUiBaselineContentRoute =
  LocaleMapappletsUiBaselineContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => LocaleMapappletsUiBaselineRouteRoute,
  } as any)
const LocaleMapappletsUiBaselineButtonsTogglesRoute =
  LocaleMapappletsUiBaselineButtonsTogglesRouteImport.update({
    id: '/buttons-toggles',
    path: '/buttons-toggles',
    getParentRoute: () => LocaleMapappletsUiBaselineRouteRoute,
  } as any)
const LocaleMapappletsUiBaselineButtonsRoute =
  LocaleMapappletsUiBaselineButtonsRouteImport.update({
    id: '/buttons',
    path: '/buttons',
    getParentRoute: () => LocaleMapappletsUiBaselineRouteRoute,
  } as any)
const LocaleMapappletsCarbonReportRoute =
  LocaleMapappletsCarbonReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => LocaleMapappletsCarbonRouteRoute,
  } as any)
const LocaleMapappletsLuonnonmetsakartatAdminRouteRoute =
  LocaleMapappletsLuonnonmetsakartatAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => LocaleMapappletsLuonnonmetsakartatRouteRoute,
  } as any)
const LocaleMapappletsCarbonPlansRouteRoute =
  LocaleMapappletsCarbonPlansRouteRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => LocaleMapappletsCarbonRouteRoute,
  } as any)
const LocaleMapappletsLuonnonmetsakartatAdminIndexRoute =
  LocaleMapappletsLuonnonmetsakartatAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleMapappletsLuonnonmetsakartatAdminRouteRoute,
  } as any)
const LocaleMapappletsCarbonPlansIndexRoute =
  LocaleMapappletsCarbonPlansIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleMapappletsCarbonPlansRouteRoute,
  } as any)
const LocaleMapappletsLuonnonmetsakartatAdminTuoRoute =
  LocaleMapappletsLuonnonmetsakartatAdminTuoRouteImport.update({
    id: '/tuo',
    path: '/tuo',
    getParentRoute: () => LocaleMapappletsLuonnonmetsakartatAdminRouteRoute,
  } as any)
const LocaleMapappletsLuonnonmetsakartatAdminImportRoute =
  LocaleMapappletsLuonnonmetsakartatAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => LocaleMapappletsLuonnonmetsakartatAdminRouteRoute,
  } as any)
const LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRoute =
  LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRouteImport.update({
    id: '/taso',
    path: '/taso',
    getParentRoute: () => LocaleMapappletsLuonnonmetsakartatAdminRouteRoute,
  } as any)
const LocaleMapappletsCarbonPlansPlanIdRouteRoute =
  LocaleMapappletsCarbonPlansPlanIdRouteRouteImport.update({
    id: '/$planId',
    path: '/$planId',
    getParentRoute: () => LocaleMapappletsCarbonPlansRouteRoute,
  } as any)
const LocaleMapappletsCarbonPlansPlanIdIndexRoute =
  LocaleMapappletsCarbonPlansPlanIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleMapappletsCarbonPlansPlanIdRouteRoute,
  } as any)
const LocaleMapappletsLuonnonmetsakartatAdminTasoSplatRoute =
  LocaleMapappletsLuonnonmetsakartatAdminTasoSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRoute,
  } as any)
const LocaleMapappletsCarbonPlansPlanIdAreasRoute =
  LocaleMapappletsCarbonPlansPlanIdAreasRouteImport.update({
    id: '/areas',
    path: '/areas',
    getParentRoute: () => LocaleMapappletsCarbonPlansPlanIdRouteRoute,
  } as any)
const LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRoute =
  LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRouteImport.update(
    {
      id: '/layer/$folayerIdSlug',
      path: '/layer/$folayerIdSlug',
      getParentRoute: () => LocaleMapappletsLuonnonmetsakartatAdminRouteRoute,
    } as any,
  )
const LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugIndexRoute =
  LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRoute,
    } as any,
  )
const LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugSettingsRoute =
  LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugSettingsRouteImport.update(
    {
      id: '/settings',
      path: '/settings',
      getParentRoute: () =>
        LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRoute,
    } as any,
  )
const LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugPicturesRoute =
  LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugPicturesRouteImport.update(
    {
      id: '/pictures',
      path: '/pictures',
      getParentRoute: () =>
        LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRoute,
    } as any,
  )
const ApiUserinfoServerRoute = ApiUserinfoServerRouteImport.update({
  id: '/api/userinfo',
  path: '/api/userinfo',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiLuonnonmetsakartatSplatServerRoute =
  ApiLuonnonmetsakartatSplatServerRouteImport.update({
    id: '/api/luonnonmetsakartat/$',
    path: '/api/luonnonmetsakartat/$',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiHiilikarttaSplatServerRoute =
  ApiHiilikarttaSplatServerRouteImport.update({
    id: '/api/hiilikartta/$',
    path: '/api/hiilikartta/$',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiMapCoreMmlTmsZXYServerRoute =
  ApiMapCoreMmlTmsZXYServerRouteImport.update({
    id: '/api/map/core/mml/tms/$z/$x/$y',
    path: '/api/map/core/mml/tms/$z/$x/$y',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleMapRouteRouteWithChildren
  '/$locale/adds/login': typeof LocaleAddsLoginRouteRouteWithChildren
  '/$locale/dev/component-fixtures': typeof LocaleDevComponentFixturesRouteRouteWithChildren
  '/$locale/': typeof LocaleMapIndexRoute
  '/$locale/carbon': typeof LocaleMapappletsCarbonRouteRouteWithChildren
  '/$locale/energy': typeof LocaleMapappletsEnergyRouteRouteWithChildren
  '/$locale/forests': typeof LocaleMapappletsForestsRouteRouteWithChildren
  '/$locale/luonnonmetsakartat': typeof LocaleMapappletsLuonnonmetsakartatRouteRouteWithChildren
  '/$locale/ui-baseline': typeof LocaleMapappletsUiBaselineRouteRouteWithChildren
  '/$locale/adds/login/callback': typeof LocaleAddsLoginCallbackRoute
  '/$locale/adds/login/': typeof LocaleAddsLoginIndexRoute
  '/$locale/dev/component-fixtures/': typeof LocaleDevComponentFixturesIndexRoute
  '/$locale/carbon/plans': typeof LocaleMapappletsCarbonPlansRouteRouteWithChildren
  '/$locale/luonnonmetsakartat/admin': typeof LocaleMapappletsLuonnonmetsakartatAdminRouteRouteWithChildren
  '/$locale/carbon/report': typeof LocaleMapappletsCarbonReportRoute
  '/$locale/ui-baseline/buttons': typeof LocaleMapappletsUiBaselineButtonsRoute
  '/$locale/ui-baseline/buttons-toggles': typeof LocaleMapappletsUiBaselineButtonsTogglesRoute
  '/$locale/ui-baseline/content': typeof LocaleMapappletsUiBaselineContentRoute
  '/$locale/ui-baseline/drawing': typeof LocaleMapappletsUiBaselineDrawingRoute
  '/$locale/ui-baseline/dropdowns': typeof LocaleMapappletsUiBaselineDropdownsRoute
  '/$locale/ui-baseline/inputs': typeof LocaleMapappletsUiBaselineInputsRoute
  '/$locale/ui-baseline/modals': typeof LocaleMapappletsUiBaselineModalsRoute
  '/$locale/ui-baseline/node-flow': typeof LocaleMapappletsUiBaselineNodeFlowRoute
  '/$locale/ui-baseline/notifications': typeof LocaleMapappletsUiBaselineNotificationsRoute
  '/$locale/ui-baseline/panels': typeof LocaleMapappletsUiBaselinePanelsRoute
  '/$locale/dev/component-fixtures/$fixtureId/$stateId': typeof LocaleDevComponentFixturesFixtureIdStateIdRoute
  '/$locale/carbon/': typeof LocaleMapappletsCarbonIndexRoute
  '/$locale/energy/': typeof LocaleMapappletsEnergyIndexRoute
  '/$locale/forests/': typeof LocaleMapappletsForestsIndexRoute
  '/$locale/luonnonmetsakartat/': typeof LocaleMapappletsLuonnonmetsakartatIndexRoute
  '/$locale/ui-baseline/': typeof LocaleMapappletsUiBaselineIndexRoute
  '/$locale/carbon/plans/$planId': typeof LocaleMapappletsCarbonPlansPlanIdRouteRouteWithChildren
  '/$locale/luonnonmetsakartat/admin/taso': typeof LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRouteWithChildren
  '/$locale/luonnonmetsakartat/admin/import': typeof LocaleMapappletsLuonnonmetsakartatAdminImportRoute
  '/$locale/luonnonmetsakartat/admin/tuo': typeof LocaleMapappletsLuonnonmetsakartatAdminTuoRoute
  '/$locale/carbon/plans/': typeof LocaleMapappletsCarbonPlansIndexRoute
  '/$locale/luonnonmetsakartat/admin/': typeof LocaleMapappletsLuonnonmetsakartatAdminIndexRoute
  '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug': typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRouteWithChildren
  '/$locale/carbon/plans/$planId/areas': typeof LocaleMapappletsCarbonPlansPlanIdAreasRoute
  '/$locale/luonnonmetsakartat/admin/taso/$': typeof LocaleMapappletsLuonnonmetsakartatAdminTasoSplatRoute
  '/$locale/carbon/plans/$planId/': typeof LocaleMapappletsCarbonPlansPlanIdIndexRoute
  '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug/pictures': typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugPicturesRoute
  '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug/settings': typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugSettingsRoute
  '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug/': typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleMapIndexRoute
  '/$locale/adds/login/callback': typeof LocaleAddsLoginCallbackRoute
  '/$locale/adds/login': typeof LocaleAddsLoginIndexRoute
  '/$locale/dev/component-fixtures': typeof LocaleDevComponentFixturesIndexRoute
  '/$locale/carbon/report': typeof LocaleMapappletsCarbonReportRoute
  '/$locale/ui-baseline/buttons': typeof LocaleMapappletsUiBaselineButtonsRoute
  '/$locale/ui-baseline/buttons-toggles': typeof LocaleMapappletsUiBaselineButtonsTogglesRoute
  '/$locale/ui-baseline/content': typeof LocaleMapappletsUiBaselineContentRoute
  '/$locale/ui-baseline/drawing': typeof LocaleMapappletsUiBaselineDrawingRoute
  '/$locale/ui-baseline/dropdowns': typeof LocaleMapappletsUiBaselineDropdownsRoute
  '/$locale/ui-baseline/inputs': typeof LocaleMapappletsUiBaselineInputsRoute
  '/$locale/ui-baseline/modals': typeof LocaleMapappletsUiBaselineModalsRoute
  '/$locale/ui-baseline/node-flow': typeof LocaleMapappletsUiBaselineNodeFlowRoute
  '/$locale/ui-baseline/notifications': typeof LocaleMapappletsUiBaselineNotificationsRoute
  '/$locale/ui-baseline/panels': typeof LocaleMapappletsUiBaselinePanelsRoute
  '/$locale/dev/component-fixtures/$fixtureId/$stateId': typeof LocaleDevComponentFixturesFixtureIdStateIdRoute
  '/$locale/carbon': typeof LocaleMapappletsCarbonIndexRoute
  '/$locale/energy': typeof LocaleMapappletsEnergyIndexRoute
  '/$locale/forests': typeof LocaleMapappletsForestsIndexRoute
  '/$locale/luonnonmetsakartat': typeof LocaleMapappletsLuonnonmetsakartatIndexRoute
  '/$locale/ui-baseline': typeof LocaleMapappletsUiBaselineIndexRoute
  '/$locale/luonnonmetsakartat/admin/taso': typeof LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRouteWithChildren
  '/$locale/luonnonmetsakartat/admin/import': typeof LocaleMapappletsLuonnonmetsakartatAdminImportRoute
  '/$locale/luonnonmetsakartat/admin/tuo': typeof LocaleMapappletsLuonnonmetsakartatAdminTuoRoute
  '/$locale/carbon/plans': typeof LocaleMapappletsCarbonPlansIndexRoute
  '/$locale/luonnonmetsakartat/admin': typeof LocaleMapappletsLuonnonmetsakartatAdminIndexRoute
  '/$locale/carbon/plans/$planId/areas': typeof LocaleMapappletsCarbonPlansPlanIdAreasRoute
  '/$locale/luonnonmetsakartat/admin/taso/$': typeof LocaleMapappletsLuonnonmetsakartatAdminTasoSplatRoute
  '/$locale/carbon/plans/$planId': typeof LocaleMapappletsCarbonPlansPlanIdIndexRoute
  '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug/pictures': typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugPicturesRoute
  '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug/settings': typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugSettingsRoute
  '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug': typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/_map': typeof LocaleMapRouteRouteWithChildren
  '/$locale/adds/login': typeof LocaleAddsLoginRouteRouteWithChildren
  '/$locale/dev/component-fixtures': typeof LocaleDevComponentFixturesRouteRouteWithChildren
  '/$locale/_map/': typeof LocaleMapIndexRoute
  '/$locale/_map/(applets)/carbon': typeof LocaleMapappletsCarbonRouteRouteWithChildren
  '/$locale/_map/(applets)/energy': typeof LocaleMapappletsEnergyRouteRouteWithChildren
  '/$locale/_map/(applets)/forests': typeof LocaleMapappletsForestsRouteRouteWithChildren
  '/$locale/_map/(applets)/luonnonmetsakartat': typeof LocaleMapappletsLuonnonmetsakartatRouteRouteWithChildren
  '/$locale/_map/(applets)/ui-baseline': typeof LocaleMapappletsUiBaselineRouteRouteWithChildren
  '/$locale/adds/login/callback': typeof LocaleAddsLoginCallbackRoute
  '/$locale/adds/login/': typeof LocaleAddsLoginIndexRoute
  '/$locale/dev/component-fixtures/': typeof LocaleDevComponentFixturesIndexRoute
  '/$locale/_map/(applets)/carbon/plans': typeof LocaleMapappletsCarbonPlansRouteRouteWithChildren
  '/$locale/_map/(applets)/luonnonmetsakartat/admin': typeof LocaleMapappletsLuonnonmetsakartatAdminRouteRouteWithChildren
  '/$locale/_map/(applets)/carbon/report': typeof LocaleMapappletsCarbonReportRoute
  '/$locale/_map/(applets)/ui-baseline/buttons': typeof LocaleMapappletsUiBaselineButtonsRoute
  '/$locale/_map/(applets)/ui-baseline/buttons-toggles': typeof LocaleMapappletsUiBaselineButtonsTogglesRoute
  '/$locale/_map/(applets)/ui-baseline/content': typeof LocaleMapappletsUiBaselineContentRoute
  '/$locale/_map/(applets)/ui-baseline/drawing': typeof LocaleMapappletsUiBaselineDrawingRoute
  '/$locale/_map/(applets)/ui-baseline/dropdowns': typeof LocaleMapappletsUiBaselineDropdownsRoute
  '/$locale/_map/(applets)/ui-baseline/inputs': typeof LocaleMapappletsUiBaselineInputsRoute
  '/$locale/_map/(applets)/ui-baseline/modals': typeof LocaleMapappletsUiBaselineModalsRoute
  '/$locale/_map/(applets)/ui-baseline/node-flow': typeof LocaleMapappletsUiBaselineNodeFlowRoute
  '/$locale/_map/(applets)/ui-baseline/notifications': typeof LocaleMapappletsUiBaselineNotificationsRoute
  '/$locale/_map/(applets)/ui-baseline/panels': typeof LocaleMapappletsUiBaselinePanelsRoute
  '/$locale/dev/component-fixtures/$fixtureId/$stateId': typeof LocaleDevComponentFixturesFixtureIdStateIdRoute
  '/$locale/_map/(applets)/carbon/': typeof LocaleMapappletsCarbonIndexRoute
  '/$locale/_map/(applets)/energy/': typeof LocaleMapappletsEnergyIndexRoute
  '/$locale/_map/(applets)/forests/': typeof LocaleMapappletsForestsIndexRoute
  '/$locale/_map/(applets)/luonnonmetsakartat/': typeof LocaleMapappletsLuonnonmetsakartatIndexRoute
  '/$locale/_map/(applets)/ui-baseline/': typeof LocaleMapappletsUiBaselineIndexRoute
  '/$locale/_map/(applets)/carbon/plans/$planId': typeof LocaleMapappletsCarbonPlansPlanIdRouteRouteWithChildren
  '/$locale/_map/(applets)/luonnonmetsakartat/admin/taso': typeof LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRouteWithChildren
  '/$locale/_map/(applets)/luonnonmetsakartat/admin/import': typeof LocaleMapappletsLuonnonmetsakartatAdminImportRoute
  '/$locale/_map/(applets)/luonnonmetsakartat/admin/tuo': typeof LocaleMapappletsLuonnonmetsakartatAdminTuoRoute
  '/$locale/_map/(applets)/carbon/plans/': typeof LocaleMapappletsCarbonPlansIndexRoute
  '/$locale/_map/(applets)/luonnonmetsakartat/admin/': typeof LocaleMapappletsLuonnonmetsakartatAdminIndexRoute
  '/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug': typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRouteWithChildren
  '/$locale/_map/(applets)/carbon/plans/$planId/areas': typeof LocaleMapappletsCarbonPlansPlanIdAreasRoute
  '/$locale/_map/(applets)/luonnonmetsakartat/admin/taso/$': typeof LocaleMapappletsLuonnonmetsakartatAdminTasoSplatRoute
  '/$locale/_map/(applets)/carbon/plans/$planId/': typeof LocaleMapappletsCarbonPlansPlanIdIndexRoute
  '/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug/pictures': typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugPicturesRoute
  '/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug/settings': typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugSettingsRoute
  '/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug/': typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/adds/login'
    | '/$locale/dev/component-fixtures'
    | '/$locale/'
    | '/$locale/carbon'
    | '/$locale/energy'
    | '/$locale/forests'
    | '/$locale/luonnonmetsakartat'
    | '/$locale/ui-baseline'
    | '/$locale/adds/login/callback'
    | '/$locale/adds/login/'
    | '/$locale/dev/component-fixtures/'
    | '/$locale/carbon/plans'
    | '/$locale/luonnonmetsakartat/admin'
    | '/$locale/carbon/report'
    | '/$locale/ui-baseline/buttons'
    | '/$locale/ui-baseline/buttons-toggles'
    | '/$locale/ui-baseline/content'
    | '/$locale/ui-baseline/drawing'
    | '/$locale/ui-baseline/dropdowns'
    | '/$locale/ui-baseline/inputs'
    | '/$locale/ui-baseline/modals'
    | '/$locale/ui-baseline/node-flow'
    | '/$locale/ui-baseline/notifications'
    | '/$locale/ui-baseline/panels'
    | '/$locale/dev/component-fixtures/$fixtureId/$stateId'
    | '/$locale/carbon/'
    | '/$locale/energy/'
    | '/$locale/forests/'
    | '/$locale/luonnonmetsakartat/'
    | '/$locale/ui-baseline/'
    | '/$locale/carbon/plans/$planId'
    | '/$locale/luonnonmetsakartat/admin/taso'
    | '/$locale/luonnonmetsakartat/admin/import'
    | '/$locale/luonnonmetsakartat/admin/tuo'
    | '/$locale/carbon/plans/'
    | '/$locale/luonnonmetsakartat/admin/'
    | '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug'
    | '/$locale/carbon/plans/$planId/areas'
    | '/$locale/luonnonmetsakartat/admin/taso/$'
    | '/$locale/carbon/plans/$planId/'
    | '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug/pictures'
    | '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug/settings'
    | '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/adds/login/callback'
    | '/$locale/adds/login'
    | '/$locale/dev/component-fixtures'
    | '/$locale/carbon/report'
    | '/$locale/ui-baseline/buttons'
    | '/$locale/ui-baseline/buttons-toggles'
    | '/$locale/ui-baseline/content'
    | '/$locale/ui-baseline/drawing'
    | '/$locale/ui-baseline/dropdowns'
    | '/$locale/ui-baseline/inputs'
    | '/$locale/ui-baseline/modals'
    | '/$locale/ui-baseline/node-flow'
    | '/$locale/ui-baseline/notifications'
    | '/$locale/ui-baseline/panels'
    | '/$locale/dev/component-fixtures/$fixtureId/$stateId'
    | '/$locale/carbon'
    | '/$locale/energy'
    | '/$locale/forests'
    | '/$locale/luonnonmetsakartat'
    | '/$locale/ui-baseline'
    | '/$locale/luonnonmetsakartat/admin/taso'
    | '/$locale/luonnonmetsakartat/admin/import'
    | '/$locale/luonnonmetsakartat/admin/tuo'
    | '/$locale/carbon/plans'
    | '/$locale/luonnonmetsakartat/admin'
    | '/$locale/carbon/plans/$planId/areas'
    | '/$locale/luonnonmetsakartat/admin/taso/$'
    | '/$locale/carbon/plans/$planId'
    | '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug/pictures'
    | '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug/settings'
    | '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/_map'
    | '/$locale/adds/login'
    | '/$locale/dev/component-fixtures'
    | '/$locale/_map/'
    | '/$locale/_map/(applets)/carbon'
    | '/$locale/_map/(applets)/energy'
    | '/$locale/_map/(applets)/forests'
    | '/$locale/_map/(applets)/luonnonmetsakartat'
    | '/$locale/_map/(applets)/ui-baseline'
    | '/$locale/adds/login/callback'
    | '/$locale/adds/login/'
    | '/$locale/dev/component-fixtures/'
    | '/$locale/_map/(applets)/carbon/plans'
    | '/$locale/_map/(applets)/luonnonmetsakartat/admin'
    | '/$locale/_map/(applets)/carbon/report'
    | '/$locale/_map/(applets)/ui-baseline/buttons'
    | '/$locale/_map/(applets)/ui-baseline/buttons-toggles'
    | '/$locale/_map/(applets)/ui-baseline/content'
    | '/$locale/_map/(applets)/ui-baseline/drawing'
    | '/$locale/_map/(applets)/ui-baseline/dropdowns'
    | '/$locale/_map/(applets)/ui-baseline/inputs'
    | '/$locale/_map/(applets)/ui-baseline/modals'
    | '/$locale/_map/(applets)/ui-baseline/node-flow'
    | '/$locale/_map/(applets)/ui-baseline/notifications'
    | '/$locale/_map/(applets)/ui-baseline/panels'
    | '/$locale/dev/component-fixtures/$fixtureId/$stateId'
    | '/$locale/_map/(applets)/carbon/'
    | '/$locale/_map/(applets)/energy/'
    | '/$locale/_map/(applets)/forests/'
    | '/$locale/_map/(applets)/luonnonmetsakartat/'
    | '/$locale/_map/(applets)/ui-baseline/'
    | '/$locale/_map/(applets)/carbon/plans/$planId'
    | '/$locale/_map/(applets)/luonnonmetsakartat/admin/taso'
    | '/$locale/_map/(applets)/luonnonmetsakartat/admin/import'
    | '/$locale/_map/(applets)/luonnonmetsakartat/admin/tuo'
    | '/$locale/_map/(applets)/carbon/plans/'
    | '/$locale/_map/(applets)/luonnonmetsakartat/admin/'
    | '/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug'
    | '/$locale/_map/(applets)/carbon/plans/$planId/areas'
    | '/$locale/_map/(applets)/luonnonmetsakartat/admin/taso/$'
    | '/$locale/_map/(applets)/carbon/plans/$planId/'
    | '/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug/pictures'
    | '/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug/settings'
    | '/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/userinfo': typeof ApiUserinfoServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/hiilikartta/$': typeof ApiHiilikarttaSplatServerRoute
  '/api/luonnonmetsakartat/$': typeof ApiLuonnonmetsakartatSplatServerRoute
  '/api/map/core/mml/tms/$z/$x/$y': typeof ApiMapCoreMmlTmsZXYServerRoute
}
export interface FileServerRoutesByTo {
  '/api/userinfo': typeof ApiUserinfoServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/hiilikartta/$': typeof ApiHiilikarttaSplatServerRoute
  '/api/luonnonmetsakartat/$': typeof ApiLuonnonmetsakartatSplatServerRoute
  '/api/map/core/mml/tms/$z/$x/$y': typeof ApiMapCoreMmlTmsZXYServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/userinfo': typeof ApiUserinfoServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/hiilikartta/$': typeof ApiHiilikarttaSplatServerRoute
  '/api/luonnonmetsakartat/$': typeof ApiLuonnonmetsakartatSplatServerRoute
  '/api/map/core/mml/tms/$z/$x/$y': typeof ApiMapCoreMmlTmsZXYServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/userinfo'
    | '/api/auth/$'
    | '/api/hiilikartta/$'
    | '/api/luonnonmetsakartat/$'
    | '/api/map/core/mml/tms/$z/$x/$y'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/userinfo'
    | '/api/auth/$'
    | '/api/hiilikartta/$'
    | '/api/luonnonmetsakartat/$'
    | '/api/map/core/mml/tms/$z/$x/$y'
  id:
    | '__root__'
    | '/api/userinfo'
    | '/api/auth/$'
    | '/api/hiilikartta/$'
    | '/api/luonnonmetsakartat/$'
    | '/api/map/core/mml/tms/$z/$x/$y'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiUserinfoServerRoute: typeof ApiUserinfoServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiHiilikarttaSplatServerRoute: typeof ApiHiilikarttaSplatServerRoute
  ApiLuonnonmetsakartatSplatServerRoute: typeof ApiLuonnonmetsakartatSplatServerRoute
  ApiMapCoreMmlTmsZXYServerRoute: typeof ApiMapCoreMmlTmsZXYServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_map': {
      id: '/$locale/_map'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleMapRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/_map/': {
      id: '/$locale/_map/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleMapIndexRouteImport
      parentRoute: typeof LocaleMapRouteRoute
    }
    '/$locale/dev/component-fixtures': {
      id: '/$locale/dev/component-fixtures'
      path: '/dev/component-fixtures'
      fullPath: '/$locale/dev/component-fixtures'
      preLoaderRoute: typeof LocaleDevComponentFixturesRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/adds/login': {
      id: '/$locale/adds/login'
      path: '/adds/login'
      fullPath: '/$locale/adds/login'
      preLoaderRoute: typeof LocaleAddsLoginRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/dev/component-fixtures/': {
      id: '/$locale/dev/component-fixtures/'
      path: '/'
      fullPath: '/$locale/dev/component-fixtures/'
      preLoaderRoute: typeof LocaleDevComponentFixturesIndexRouteImport
      parentRoute: typeof LocaleDevComponentFixturesRouteRoute
    }
    '/$locale/adds/login/': {
      id: '/$locale/adds/login/'
      path: '/'
      fullPath: '/$locale/adds/login/'
      preLoaderRoute: typeof LocaleAddsLoginIndexRouteImport
      parentRoute: typeof LocaleAddsLoginRouteRoute
    }
    '/$locale/adds/login/callback': {
      id: '/$locale/adds/login/callback'
      path: '/callback'
      fullPath: '/$locale/adds/login/callback'
      preLoaderRoute: typeof LocaleAddsLoginCallbackRouteImport
      parentRoute: typeof LocaleAddsLoginRouteRoute
    }
    '/$locale/_map/(applets)/ui-baseline': {
      id: '/$locale/_map/(applets)/ui-baseline'
      path: '/ui-baseline'
      fullPath: '/$locale/ui-baseline'
      preLoaderRoute: typeof LocaleMapappletsUiBaselineRouteRouteImport
      parentRoute: typeof LocaleMapRouteRoute
    }
    '/$locale/_map/(applets)/luonnonmetsakartat': {
      id: '/$locale/_map/(applets)/luonnonmetsakartat'
      path: '/luonnonmetsakartat'
      fullPath: '/$locale/luonnonmetsakartat'
      preLoaderRoute: typeof LocaleMapappletsLuonnonmetsakartatRouteRouteImport
      parentRoute: typeof LocaleMapRouteRoute
    }
    '/$locale/_map/(applets)/forests': {
      id: '/$locale/_map/(applets)/forests'
      path: '/forests'
      fullPath: '/$locale/forests'
      preLoaderRoute: typeof LocaleMapappletsForestsRouteRouteImport
      parentRoute: typeof LocaleMapRouteRoute
    }
    '/$locale/_map/(applets)/energy': {
      id: '/$locale/_map/(applets)/energy'
      path: '/energy'
      fullPath: '/$locale/energy'
      preLoaderRoute: typeof LocaleMapappletsEnergyRouteRouteImport
      parentRoute: typeof LocaleMapRouteRoute
    }
    '/$locale/_map/(applets)/carbon': {
      id: '/$locale/_map/(applets)/carbon'
      path: '/carbon'
      fullPath: '/$locale/carbon'
      preLoaderRoute: typeof LocaleMapappletsCarbonRouteRouteImport
      parentRoute: typeof LocaleMapRouteRoute
    }
    '/$locale/_map/(applets)/ui-baseline/': {
      id: '/$locale/_map/(applets)/ui-baseline/'
      path: '/'
      fullPath: '/$locale/ui-baseline/'
      preLoaderRoute: typeof LocaleMapappletsUiBaselineIndexRouteImport
      parentRoute: typeof LocaleMapappletsUiBaselineRouteRoute
    }
    '/$locale/_map/(applets)/luonnonmetsakartat/': {
      id: '/$locale/_map/(applets)/luonnonmetsakartat/'
      path: '/'
      fullPath: '/$locale/luonnonmetsakartat/'
      preLoaderRoute: typeof LocaleMapappletsLuonnonmetsakartatIndexRouteImport
      parentRoute: typeof LocaleMapappletsLuonnonmetsakartatRouteRoute
    }
    '/$locale/_map/(applets)/forests/': {
      id: '/$locale/_map/(applets)/forests/'
      path: '/'
      fullPath: '/$locale/forests/'
      preLoaderRoute: typeof LocaleMapappletsForestsIndexRouteImport
      parentRoute: typeof LocaleMapappletsForestsRouteRoute
    }
    '/$locale/_map/(applets)/energy/': {
      id: '/$locale/_map/(applets)/energy/'
      path: '/'
      fullPath: '/$locale/energy/'
      preLoaderRoute: typeof LocaleMapappletsEnergyIndexRouteImport
      parentRoute: typeof LocaleMapappletsEnergyRouteRoute
    }
    '/$locale/_map/(applets)/carbon/': {
      id: '/$locale/_map/(applets)/carbon/'
      path: '/'
      fullPath: '/$locale/carbon/'
      preLoaderRoute: typeof LocaleMapappletsCarbonIndexRouteImport
      parentRoute: typeof LocaleMapappletsCarbonRouteRoute
    }
    '/$locale/dev/component-fixtures/$fixtureId/$stateId': {
      id: '/$locale/dev/component-fixtures/$fixtureId/$stateId'
      path: '/$fixtureId/$stateId'
      fullPath: '/$locale/dev/component-fixtures/$fixtureId/$stateId'
      preLoaderRoute: typeof LocaleDevComponentFixturesFixtureIdStateIdRouteImport
      parentRoute: typeof LocaleDevComponentFixturesRouteRoute
    }
    '/$locale/_map/(applets)/ui-baseline/panels': {
      id: '/$locale/_map/(applets)/ui-baseline/panels'
      path: '/panels'
      fullPath: '/$locale/ui-baseline/panels'
      preLoaderRoute: typeof LocaleMapappletsUiBaselinePanelsRouteImport
      parentRoute: typeof LocaleMapappletsUiBaselineRouteRoute
    }
    '/$locale/_map/(applets)/ui-baseline/notifications': {
      id: '/$locale/_map/(applets)/ui-baseline/notifications'
      path: '/notifications'
      fullPath: '/$locale/ui-baseline/notifications'
      preLoaderRoute: typeof LocaleMapappletsUiBaselineNotificationsRouteImport
      parentRoute: typeof LocaleMapappletsUiBaselineRouteRoute
    }
    '/$locale/_map/(applets)/ui-baseline/node-flow': {
      id: '/$locale/_map/(applets)/ui-baseline/node-flow'
      path: '/node-flow'
      fullPath: '/$locale/ui-baseline/node-flow'
      preLoaderRoute: typeof LocaleMapappletsUiBaselineNodeFlowRouteImport
      parentRoute: typeof LocaleMapappletsUiBaselineRouteRoute
    }
    '/$locale/_map/(applets)/ui-baseline/modals': {
      id: '/$locale/_map/(applets)/ui-baseline/modals'
      path: '/modals'
      fullPath: '/$locale/ui-baseline/modals'
      preLoaderRoute: typeof LocaleMapappletsUiBaselineModalsRouteImport
      parentRoute: typeof LocaleMapappletsUiBaselineRouteRoute
    }
    '/$locale/_map/(applets)/ui-baseline/inputs': {
      id: '/$locale/_map/(applets)/ui-baseline/inputs'
      path: '/inputs'
      fullPath: '/$locale/ui-baseline/inputs'
      preLoaderRoute: typeof LocaleMapappletsUiBaselineInputsRouteImport
      parentRoute: typeof LocaleMapappletsUiBaselineRouteRoute
    }
    '/$locale/_map/(applets)/ui-baseline/dropdowns': {
      id: '/$locale/_map/(applets)/ui-baseline/dropdowns'
      path: '/dropdowns'
      fullPath: '/$locale/ui-baseline/dropdowns'
      preLoaderRoute: typeof LocaleMapappletsUiBaselineDropdownsRouteImport
      parentRoute: typeof LocaleMapappletsUiBaselineRouteRoute
    }
    '/$locale/_map/(applets)/ui-baseline/drawing': {
      id: '/$locale/_map/(applets)/ui-baseline/drawing'
      path: '/drawing'
      fullPath: '/$locale/ui-baseline/drawing'
      preLoaderRoute: typeof LocaleMapappletsUiBaselineDrawingRouteImport
      parentRoute: typeof LocaleMapappletsUiBaselineRouteRoute
    }
    '/$locale/_map/(applets)/ui-baseline/content': {
      id: '/$locale/_map/(applets)/ui-baseline/content'
      path: '/content'
      fullPath: '/$locale/ui-baseline/content'
      preLoaderRoute: typeof LocaleMapappletsUiBaselineContentRouteImport
      parentRoute: typeof LocaleMapappletsUiBaselineRouteRoute
    }
    '/$locale/_map/(applets)/ui-baseline/buttons-toggles': {
      id: '/$locale/_map/(applets)/ui-baseline/buttons-toggles'
      path: '/buttons-toggles'
      fullPath: '/$locale/ui-baseline/buttons-toggles'
      preLoaderRoute: typeof LocaleMapappletsUiBaselineButtonsTogglesRouteImport
      parentRoute: typeof LocaleMapappletsUiBaselineRouteRoute
    }
    '/$locale/_map/(applets)/ui-baseline/buttons': {
      id: '/$locale/_map/(applets)/ui-baseline/buttons'
      path: '/buttons'
      fullPath: '/$locale/ui-baseline/buttons'
      preLoaderRoute: typeof LocaleMapappletsUiBaselineButtonsRouteImport
      parentRoute: typeof LocaleMapappletsUiBaselineRouteRoute
    }
    '/$locale/_map/(applets)/carbon/report': {
      id: '/$locale/_map/(applets)/carbon/report'
      path: '/report'
      fullPath: '/$locale/carbon/report'
      preLoaderRoute: typeof LocaleMapappletsCarbonReportRouteImport
      parentRoute: typeof LocaleMapappletsCarbonRouteRoute
    }
    '/$locale/_map/(applets)/luonnonmetsakartat/admin': {
      id: '/$locale/_map/(applets)/luonnonmetsakartat/admin'
      path: '/admin'
      fullPath: '/$locale/luonnonmetsakartat/admin'
      preLoaderRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminRouteRouteImport
      parentRoute: typeof LocaleMapappletsLuonnonmetsakartatRouteRoute
    }
    '/$locale/_map/(applets)/carbon/plans': {
      id: '/$locale/_map/(applets)/carbon/plans'
      path: '/plans'
      fullPath: '/$locale/carbon/plans'
      preLoaderRoute: typeof LocaleMapappletsCarbonPlansRouteRouteImport
      parentRoute: typeof LocaleMapappletsCarbonRouteRoute
    }
    '/$locale/_map/(applets)/luonnonmetsakartat/admin/': {
      id: '/$locale/_map/(applets)/luonnonmetsakartat/admin/'
      path: '/'
      fullPath: '/$locale/luonnonmetsakartat/admin/'
      preLoaderRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminIndexRouteImport
      parentRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminRouteRoute
    }
    '/$locale/_map/(applets)/carbon/plans/': {
      id: '/$locale/_map/(applets)/carbon/plans/'
      path: '/'
      fullPath: '/$locale/carbon/plans/'
      preLoaderRoute: typeof LocaleMapappletsCarbonPlansIndexRouteImport
      parentRoute: typeof LocaleMapappletsCarbonPlansRouteRoute
    }
    '/$locale/_map/(applets)/luonnonmetsakartat/admin/tuo': {
      id: '/$locale/_map/(applets)/luonnonmetsakartat/admin/tuo'
      path: '/tuo'
      fullPath: '/$locale/luonnonmetsakartat/admin/tuo'
      preLoaderRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminTuoRouteImport
      parentRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminRouteRoute
    }
    '/$locale/_map/(applets)/luonnonmetsakartat/admin/import': {
      id: '/$locale/_map/(applets)/luonnonmetsakartat/admin/import'
      path: '/import'
      fullPath: '/$locale/luonnonmetsakartat/admin/import'
      preLoaderRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminImportRouteImport
      parentRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminRouteRoute
    }
    '/$locale/_map/(applets)/luonnonmetsakartat/admin/taso': {
      id: '/$locale/_map/(applets)/luonnonmetsakartat/admin/taso'
      path: '/taso'
      fullPath: '/$locale/luonnonmetsakartat/admin/taso'
      preLoaderRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRouteImport
      parentRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminRouteRoute
    }
    '/$locale/_map/(applets)/carbon/plans/$planId': {
      id: '/$locale/_map/(applets)/carbon/plans/$planId'
      path: '/$planId'
      fullPath: '/$locale/carbon/plans/$planId'
      preLoaderRoute: typeof LocaleMapappletsCarbonPlansPlanIdRouteRouteImport
      parentRoute: typeof LocaleMapappletsCarbonPlansRouteRoute
    }
    '/$locale/_map/(applets)/carbon/plans/$planId/': {
      id: '/$locale/_map/(applets)/carbon/plans/$planId/'
      path: '/'
      fullPath: '/$locale/carbon/plans/$planId/'
      preLoaderRoute: typeof LocaleMapappletsCarbonPlansPlanIdIndexRouteImport
      parentRoute: typeof LocaleMapappletsCarbonPlansPlanIdRouteRoute
    }
    '/$locale/_map/(applets)/luonnonmetsakartat/admin/taso/$': {
      id: '/$locale/_map/(applets)/luonnonmetsakartat/admin/taso/$'
      path: '/$'
      fullPath: '/$locale/luonnonmetsakartat/admin/taso/$'
      preLoaderRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminTasoSplatRouteImport
      parentRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRoute
    }
    '/$locale/_map/(applets)/carbon/plans/$planId/areas': {
      id: '/$locale/_map/(applets)/carbon/plans/$planId/areas'
      path: '/areas'
      fullPath: '/$locale/carbon/plans/$planId/areas'
      preLoaderRoute: typeof LocaleMapappletsCarbonPlansPlanIdAreasRouteImport
      parentRoute: typeof LocaleMapappletsCarbonPlansPlanIdRouteRoute
    }
    '/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug': {
      id: '/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug'
      path: '/layer/$folayerIdSlug'
      fullPath: '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug'
      preLoaderRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRouteImport
      parentRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminRouteRoute
    }
    '/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug/': {
      id: '/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug/'
      path: '/'
      fullPath: '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug/'
      preLoaderRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugIndexRouteImport
      parentRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRoute
    }
    '/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug/settings': {
      id: '/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug/settings'
      path: '/settings'
      fullPath: '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug/settings'
      preLoaderRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugSettingsRouteImport
      parentRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRoute
    }
    '/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug/pictures': {
      id: '/$locale/_map/(applets)/luonnonmetsakartat/admin/layer/$folayerIdSlug/pictures'
      path: '/pictures'
      fullPath: '/$locale/luonnonmetsakartat/admin/layer/$folayerIdSlug/pictures'
      preLoaderRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugPicturesRouteImport
      parentRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/userinfo': {
      id: '/api/userinfo'
      path: '/api/userinfo'
      fullPath: '/api/userinfo'
      preLoaderRoute: typeof ApiUserinfoServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/luonnonmetsakartat/$': {
      id: '/api/luonnonmetsakartat/$'
      path: '/api/luonnonmetsakartat/$'
      fullPath: '/api/luonnonmetsakartat/$'
      preLoaderRoute: typeof ApiLuonnonmetsakartatSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/hiilikartta/$': {
      id: '/api/hiilikartta/$'
      path: '/api/hiilikartta/$'
      fullPath: '/api/hiilikartta/$'
      preLoaderRoute: typeof ApiHiilikarttaSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/map/core/mml/tms/$z/$x/$y': {
      id: '/api/map/core/mml/tms/$z/$x/$y'
      path: '/api/map/core/mml/tms/$z/$x/$y'
      fullPath: '/api/map/core/mml/tms/$z/$x/$y'
      preLoaderRoute: typeof ApiMapCoreMmlTmsZXYServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface LocaleMapappletsCarbonPlansPlanIdRouteRouteChildren {
  LocaleMapappletsCarbonPlansPlanIdAreasRoute: typeof LocaleMapappletsCarbonPlansPlanIdAreasRoute
  LocaleMapappletsCarbonPlansPlanIdIndexRoute: typeof LocaleMapappletsCarbonPlansPlanIdIndexRoute
}

const LocaleMapappletsCarbonPlansPlanIdRouteRouteChildren: LocaleMapappletsCarbonPlansPlanIdRouteRouteChildren =
  {
    LocaleMapappletsCarbonPlansPlanIdAreasRoute:
      LocaleMapappletsCarbonPlansPlanIdAreasRoute,
    LocaleMapappletsCarbonPlansPlanIdIndexRoute:
      LocaleMapappletsCarbonPlansPlanIdIndexRoute,
  }

const LocaleMapappletsCarbonPlansPlanIdRouteRouteWithChildren =
  LocaleMapappletsCarbonPlansPlanIdRouteRoute._addFileChildren(
    LocaleMapappletsCarbonPlansPlanIdRouteRouteChildren,
  )

interface LocaleMapappletsCarbonPlansRouteRouteChildren {
  LocaleMapappletsCarbonPlansPlanIdRouteRoute: typeof LocaleMapappletsCarbonPlansPlanIdRouteRouteWithChildren
  LocaleMapappletsCarbonPlansIndexRoute: typeof LocaleMapappletsCarbonPlansIndexRoute
}

const LocaleMapappletsCarbonPlansRouteRouteChildren: LocaleMapappletsCarbonPlansRouteRouteChildren =
  {
    LocaleMapappletsCarbonPlansPlanIdRouteRoute:
      LocaleMapappletsCarbonPlansPlanIdRouteRouteWithChildren,
    LocaleMapappletsCarbonPlansIndexRoute:
      LocaleMapappletsCarbonPlansIndexRoute,
  }

const LocaleMapappletsCarbonPlansRouteRouteWithChildren =
  LocaleMapappletsCarbonPlansRouteRoute._addFileChildren(
    LocaleMapappletsCarbonPlansRouteRouteChildren,
  )

interface LocaleMapappletsCarbonRouteRouteChildren {
  LocaleMapappletsCarbonPlansRouteRoute: typeof LocaleMapappletsCarbonPlansRouteRouteWithChildren
  LocaleMapappletsCarbonReportRoute: typeof LocaleMapappletsCarbonReportRoute
  LocaleMapappletsCarbonIndexRoute: typeof LocaleMapappletsCarbonIndexRoute
}

const LocaleMapappletsCarbonRouteRouteChildren: LocaleMapappletsCarbonRouteRouteChildren =
  {
    LocaleMapappletsCarbonPlansRouteRoute:
      LocaleMapappletsCarbonPlansRouteRouteWithChildren,
    LocaleMapappletsCarbonReportRoute: LocaleMapappletsCarbonReportRoute,
    LocaleMapappletsCarbonIndexRoute: LocaleMapappletsCarbonIndexRoute,
  }

const LocaleMapappletsCarbonRouteRouteWithChildren =
  LocaleMapappletsCarbonRouteRoute._addFileChildren(
    LocaleMapappletsCarbonRouteRouteChildren,
  )

interface LocaleMapappletsEnergyRouteRouteChildren {
  LocaleMapappletsEnergyIndexRoute: typeof LocaleMapappletsEnergyIndexRoute
}

const LocaleMapappletsEnergyRouteRouteChildren: LocaleMapappletsEnergyRouteRouteChildren =
  {
    LocaleMapappletsEnergyIndexRoute: LocaleMapappletsEnergyIndexRoute,
  }

const LocaleMapappletsEnergyRouteRouteWithChildren =
  LocaleMapappletsEnergyRouteRoute._addFileChildren(
    LocaleMapappletsEnergyRouteRouteChildren,
  )

interface LocaleMapappletsForestsRouteRouteChildren {
  LocaleMapappletsForestsIndexRoute: typeof LocaleMapappletsForestsIndexRoute
}

const LocaleMapappletsForestsRouteRouteChildren: LocaleMapappletsForestsRouteRouteChildren =
  {
    LocaleMapappletsForestsIndexRoute: LocaleMapappletsForestsIndexRoute,
  }

const LocaleMapappletsForestsRouteRouteWithChildren =
  LocaleMapappletsForestsRouteRoute._addFileChildren(
    LocaleMapappletsForestsRouteRouteChildren,
  )

interface LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRouteChildren {
  LocaleMapappletsLuonnonmetsakartatAdminTasoSplatRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminTasoSplatRoute
}

const LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRouteChildren: LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRouteChildren =
  {
    LocaleMapappletsLuonnonmetsakartatAdminTasoSplatRoute:
      LocaleMapappletsLuonnonmetsakartatAdminTasoSplatRoute,
  }

const LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRouteWithChildren =
  LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRoute._addFileChildren(
    LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRouteChildren,
  )

interface LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRouteChildren {
  LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugPicturesRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugPicturesRoute
  LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugSettingsRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugSettingsRoute
  LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugIndexRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugIndexRoute
}

const LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRouteChildren: LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRouteChildren =
  {
    LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugPicturesRoute:
      LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugPicturesRoute,
    LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugSettingsRoute:
      LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugSettingsRoute,
    LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugIndexRoute:
      LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugIndexRoute,
  }

const LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRouteWithChildren =
  LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRoute._addFileChildren(
    LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRouteChildren,
  )

interface LocaleMapappletsLuonnonmetsakartatAdminRouteRouteChildren {
  LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRouteWithChildren
  LocaleMapappletsLuonnonmetsakartatAdminImportRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminImportRoute
  LocaleMapappletsLuonnonmetsakartatAdminTuoRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminTuoRoute
  LocaleMapappletsLuonnonmetsakartatAdminIndexRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminIndexRoute
  LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRouteWithChildren
}

const LocaleMapappletsLuonnonmetsakartatAdminRouteRouteChildren: LocaleMapappletsLuonnonmetsakartatAdminRouteRouteChildren =
  {
    LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRoute:
      LocaleMapappletsLuonnonmetsakartatAdminTasoRouteRouteWithChildren,
    LocaleMapappletsLuonnonmetsakartatAdminImportRoute:
      LocaleMapappletsLuonnonmetsakartatAdminImportRoute,
    LocaleMapappletsLuonnonmetsakartatAdminTuoRoute:
      LocaleMapappletsLuonnonmetsakartatAdminTuoRoute,
    LocaleMapappletsLuonnonmetsakartatAdminIndexRoute:
      LocaleMapappletsLuonnonmetsakartatAdminIndexRoute,
    LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRoute:
      LocaleMapappletsLuonnonmetsakartatAdminLayerFolayerIdSlugRouteRouteWithChildren,
  }

const LocaleMapappletsLuonnonmetsakartatAdminRouteRouteWithChildren =
  LocaleMapappletsLuonnonmetsakartatAdminRouteRoute._addFileChildren(
    LocaleMapappletsLuonnonmetsakartatAdminRouteRouteChildren,
  )

interface LocaleMapappletsLuonnonmetsakartatRouteRouteChildren {
  LocaleMapappletsLuonnonmetsakartatAdminRouteRoute: typeof LocaleMapappletsLuonnonmetsakartatAdminRouteRouteWithChildren
  LocaleMapappletsLuonnonmetsakartatIndexRoute: typeof LocaleMapappletsLuonnonmetsakartatIndexRoute
}

const LocaleMapappletsLuonnonmetsakartatRouteRouteChildren: LocaleMapappletsLuonnonmetsakartatRouteRouteChildren =
  {
    LocaleMapappletsLuonnonmetsakartatAdminRouteRoute:
      LocaleMapappletsLuonnonmetsakartatAdminRouteRouteWithChildren,
    LocaleMapappletsLuonnonmetsakartatIndexRoute:
      LocaleMapappletsLuonnonmetsakartatIndexRoute,
  }

const LocaleMapappletsLuonnonmetsakartatRouteRouteWithChildren =
  LocaleMapappletsLuonnonmetsakartatRouteRoute._addFileChildren(
    LocaleMapappletsLuonnonmetsakartatRouteRouteChildren,
  )

interface LocaleMapappletsUiBaselineRouteRouteChildren {
  LocaleMapappletsUiBaselineButtonsRoute: typeof LocaleMapappletsUiBaselineButtonsRoute
  LocaleMapappletsUiBaselineButtonsTogglesRoute: typeof LocaleMapappletsUiBaselineButtonsTogglesRoute
  LocaleMapappletsUiBaselineContentRoute: typeof LocaleMapappletsUiBaselineContentRoute
  LocaleMapappletsUiBaselineDrawingRoute: typeof LocaleMapappletsUiBaselineDrawingRoute
  LocaleMapappletsUiBaselineDropdownsRoute: typeof LocaleMapappletsUiBaselineDropdownsRoute
  LocaleMapappletsUiBaselineInputsRoute: typeof LocaleMapappletsUiBaselineInputsRoute
  LocaleMapappletsUiBaselineModalsRoute: typeof LocaleMapappletsUiBaselineModalsRoute
  LocaleMapappletsUiBaselineNodeFlowRoute: typeof LocaleMapappletsUiBaselineNodeFlowRoute
  LocaleMapappletsUiBaselineNotificationsRoute: typeof LocaleMapappletsUiBaselineNotificationsRoute
  LocaleMapappletsUiBaselinePanelsRoute: typeof LocaleMapappletsUiBaselinePanelsRoute
  LocaleMapappletsUiBaselineIndexRoute: typeof LocaleMapappletsUiBaselineIndexRoute
}

const LocaleMapappletsUiBaselineRouteRouteChildren: LocaleMapappletsUiBaselineRouteRouteChildren =
  {
    LocaleMapappletsUiBaselineButtonsRoute:
      LocaleMapappletsUiBaselineButtonsRoute,
    LocaleMapappletsUiBaselineButtonsTogglesRoute:
      LocaleMapappletsUiBaselineButtonsTogglesRoute,
    LocaleMapappletsUiBaselineContentRoute:
      LocaleMapappletsUiBaselineContentRoute,
    LocaleMapappletsUiBaselineDrawingRoute:
      LocaleMapappletsUiBaselineDrawingRoute,
    LocaleMapappletsUiBaselineDropdownsRoute:
      LocaleMapappletsUiBaselineDropdownsRoute,
    LocaleMapappletsUiBaselineInputsRoute:
      LocaleMapappletsUiBaselineInputsRoute,
    LocaleMapappletsUiBaselineModalsRoute:
      LocaleMapappletsUiBaselineModalsRoute,
    LocaleMapappletsUiBaselineNodeFlowRoute:
      LocaleMapappletsUiBaselineNodeFlowRoute,
    LocaleMapappletsUiBaselineNotificationsRoute:
      LocaleMapappletsUiBaselineNotificationsRoute,
    LocaleMapappletsUiBaselinePanelsRoute:
      LocaleMapappletsUiBaselinePanelsRoute,
    LocaleMapappletsUiBaselineIndexRoute: LocaleMapappletsUiBaselineIndexRoute,
  }

const LocaleMapappletsUiBaselineRouteRouteWithChildren =
  LocaleMapappletsUiBaselineRouteRoute._addFileChildren(
    LocaleMapappletsUiBaselineRouteRouteChildren,
  )

interface LocaleMapRouteRouteChildren {
  LocaleMapIndexRoute: typeof LocaleMapIndexRoute
  LocaleMapappletsCarbonRouteRoute: typeof LocaleMapappletsCarbonRouteRouteWithChildren
  LocaleMapappletsEnergyRouteRoute: typeof LocaleMapappletsEnergyRouteRouteWithChildren
  LocaleMapappletsForestsRouteRoute: typeof LocaleMapappletsForestsRouteRouteWithChildren
  LocaleMapappletsLuonnonmetsakartatRouteRoute: typeof LocaleMapappletsLuonnonmetsakartatRouteRouteWithChildren
  LocaleMapappletsUiBaselineRouteRoute: typeof LocaleMapappletsUiBaselineRouteRouteWithChildren
}

const LocaleMapRouteRouteChildren: LocaleMapRouteRouteChildren = {
  LocaleMapIndexRoute: LocaleMapIndexRoute,
  LocaleMapappletsCarbonRouteRoute:
    LocaleMapappletsCarbonRouteRouteWithChildren,
  LocaleMapappletsEnergyRouteRoute:
    LocaleMapappletsEnergyRouteRouteWithChildren,
  LocaleMapappletsForestsRouteRoute:
    LocaleMapappletsForestsRouteRouteWithChildren,
  LocaleMapappletsLuonnonmetsakartatRouteRoute:
    LocaleMapappletsLuonnonmetsakartatRouteRouteWithChildren,
  LocaleMapappletsUiBaselineRouteRoute:
    LocaleMapappletsUiBaselineRouteRouteWithChildren,
}

const LocaleMapRouteRouteWithChildren = LocaleMapRouteRoute._addFileChildren(
  LocaleMapRouteRouteChildren,
)

interface LocaleAddsLoginRouteRouteChildren {
  LocaleAddsLoginCallbackRoute: typeof LocaleAddsLoginCallbackRoute
  LocaleAddsLoginIndexRoute: typeof LocaleAddsLoginIndexRoute
}

const LocaleAddsLoginRouteRouteChildren: LocaleAddsLoginRouteRouteChildren = {
  LocaleAddsLoginCallbackRoute: LocaleAddsLoginCallbackRoute,
  LocaleAddsLoginIndexRoute: LocaleAddsLoginIndexRoute,
}

const LocaleAddsLoginRouteRouteWithChildren =
  LocaleAddsLoginRouteRoute._addFileChildren(LocaleAddsLoginRouteRouteChildren)

interface LocaleDevComponentFixturesRouteRouteChildren {
  LocaleDevComponentFixturesIndexRoute: typeof LocaleDevComponentFixturesIndexRoute
  LocaleDevComponentFixturesFixtureIdStateIdRoute: typeof LocaleDevComponentFixturesFixtureIdStateIdRoute
}

const LocaleDevComponentFixturesRouteRouteChildren: LocaleDevComponentFixturesRouteRouteChildren =
  {
    LocaleDevComponentFixturesIndexRoute: LocaleDevComponentFixturesIndexRoute,
    LocaleDevComponentFixturesFixtureIdStateIdRoute:
      LocaleDevComponentFixturesFixtureIdStateIdRoute,
  }

const LocaleDevComponentFixturesRouteRouteWithChildren =
  LocaleDevComponentFixturesRouteRoute._addFileChildren(
    LocaleDevComponentFixturesRouteRouteChildren,
  )

interface LocaleRouteRouteChildren {
  LocaleMapRouteRoute: typeof LocaleMapRouteRouteWithChildren
  LocaleAddsLoginRouteRoute: typeof LocaleAddsLoginRouteRouteWithChildren
  LocaleDevComponentFixturesRouteRoute: typeof LocaleDevComponentFixturesRouteRouteWithChildren
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleMapRouteRoute: LocaleMapRouteRouteWithChildren,
  LocaleAddsLoginRouteRoute: LocaleAddsLoginRouteRouteWithChildren,
  LocaleDevComponentFixturesRouteRoute:
    LocaleDevComponentFixturesRouteRouteWithChildren,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiUserinfoServerRoute: ApiUserinfoServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiHiilikarttaSplatServerRoute: ApiHiilikarttaSplatServerRoute,
  ApiLuonnonmetsakartatSplatServerRoute: ApiLuonnonmetsakartatSplatServerRoute,
  ApiMapCoreMmlTmsZXYServerRoute: ApiMapCoreMmlTmsZXYServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
